---
- name: Install openjdk on windows servers
  hosts: windows
  gather_facts: no
  become: yes
  become_user: Administrateur
  vars:
    openjdk_dir_src: "/home/abdelkrim"
    openjdk_dir_tmp: "C:\\temp\\openjdk_tmp\\"
    openjdk_major_Version: "11"
    openjdk_app_dir: "C:\\Program Files\\java\\"

  tasks:
    - name: Create a temporary directory for openjdk
      win_file:
        path: "{{ openjdk_dir_tmp }}"
        state: directory

    - name: Copy file openjdk{{ openjdk_major_Version }} from source server to target server (Temporaire will be replaced by Nexus)
      win_copy:
        src: "{{ item }}"
        dest: "{{ openjdk_dir_tmp }}"
      with_fileglob:
        - "{{ openjdk_dir_src }}/java-{{ openjdk_major_Version }}-openjdk-{{ openjdk_major_Version }}.*.windows.redhat.x86_64.zip"
      register: check_copy_openjdk_file

    - name: Check if openjdk{{ openjdk_major_Version }} file exists
      win_stat:
          path: "{{ openjdk_dir_tmp }}\\{{ check_copy_openjdk_file.results[0].original_basename }}"
      register: check_openjdk_file
      when: check_copy_openjdk_file.changed == False

    - name: Install openjdk{{ openjdk_major_Version }}
      block:
        - name: Extract opnejdk from temp directory to app directory
          win_unzip:
            dest: "{{ openjdk_app_dir }}"
            src: "{{ openjdk_dir_tmp }}\\{{ check_copy_openjdk_file.results[0].original_basename }}"

        - name: Rename openjdk file
          win_shell: |
            $fileName= (Get-ChildItem -Path "{{ openjdk_app_dir }}").Name
            if($fileName -match '^(java-)(.+[a-z]-)(.*[1-9].+)$'){
              $newFileName= $fileName -replace '^(java-)(.+[a-z]-)(.*[1-9])(-\d\..*)$','$1$3'
              Rename-Item "{{ openjdk_app_dir }}$fileName" $newFileName
              write-host $newFileName
            } 
          register: rename_result_out
          changed_when: rename_result_out.stdout | length != 0
        
        - name: Create Environment variable JAVA_HOME for openjdk{{openjdk_major_Version}}
          win_path:
            elements: "{{ openjdk_app_dir }}{{rename_result_out.stdout_lines[0]}}"
            scope: machine
            state: present
            name: JAVA_HOME
          when: rename_result_out.changed

        - name: Create the global system path for openjdk{{openjdk_major_Version}}
          win_path:
            elements:
            - '%JAVA_HOME%\bin'
            scope: machine
            state: present
          when: rename_result_out.changed
          
      when: check_copy_openjdk_file.changed == True or check_openjdk_file.stat.exists == True