---
- name: Update
  hosts: windows
  tasks:
    - name: update windows
      win_updates:
      register: update_result
    - debug: var=update_result

    - name : reboot if required
      win_reboot:
      reboot_timeout: 3600
      when: update_result.reboot_required